# TCL File Generated by Altera University Program
# DO NOT MODIFY

# Create a new driver - this name must be different than the 
# Le nom dans la commande : "create_driver <nom_a_donner>_driver" doit etre issu de l'entity du component HDL)
create_driver seg7_if_driver

# Associate it with some hardware 
# Attention : 
#             - dans la commande : "set_sw_property hw_class_name <nom_a_donner>"
#             - Le nom hw_class_name doit commencer etre la racine du <nom_a_donner>_driver
#             - les fichiers sources doivent avoir la meme racine <nom_a_donner> ==> seg7_if.c & seg7_if.h)
set_sw_property hw_class_name seg7_if

# The version of this driver is "1.0"
set_sw_property version 1.0

# This driver is proclaimed to be compatible with 'component'
# as old as version "9.0". The component hardware version is set in the 
# _hw.tcl file - If the hardware component  version number is not equal 
# or greater than the min_compatable_hw_version number, the driver 
# source files will not be copied over to the BSP driver directory
set_sw_property min_compatible_hw_version 1.0

# Initialize the driver in alt_sys_init()
set_sw_property auto_initialize true

# Location in generated BSP that sources will be copied into
set_sw_property bsp_subdirectory drivers

#
# Source file listings...
#

# C/C++ source files (mieux utiliser arborescence HAL/inc et HAL/src ==> meme organisation BSP genere)
add_sw_property c_source HAL/src/seg7_if.c

# Include files
add_sw_property include_source HAL/inc/seg7_if.h

# This driver supports HAL type
add_sw_property supported_bsp_type HAL

# End of file