# TCL File Generated by Component Editor 11.1
# Sun Dec 25 13:45:27 CET 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | seg7_if "seg7_if" v1.0
# | VHDL version (L. Kessal) 2011.12.25.13:45:27
# | 
# | 
# | D:/DE2_70_EXPLES/SEG7_IP/ip/TERASIC_SEG7/hdl/seg7_if.vhd
# | 
# |    ./seg7_if.vhd syn
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module seg7_if
# | 
set_module_property DESCRIPTION ""
set_module_property NAME seg7_if
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Terasic Technologies Inc."
set_module_property AUTHOR "VHDL version (L. Kessal)"
set_module_property DISPLAY_NAME seg7_if
set_module_property TOP_LEVEL_HDL_FILE seg7_if.vhd
set_module_property TOP_LEVEL_HDL_MODULE seg7_if
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME ""
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file seg7_if.vhd SYNTHESIS
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter SEG7_NUM INTEGER 8 ""
set_parameter_property SEG7_NUM DEFAULT_VALUE 8
set_parameter_property SEG7_NUM DISPLAY_NAME SEG7_NUM
set_parameter_property SEG7_NUM TYPE INTEGER
set_parameter_property SEG7_NUM UNITS None
set_parameter_property SEG7_NUM ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SEG7_NUM DESCRIPTION ""
set_parameter_property SEG7_NUM AFFECTS_GENERATION false
set_parameter_property SEG7_NUM HDL_PARAMETER true
add_parameter ADDR_WIDTH INTEGER 3 ""
set_parameter_property ADDR_WIDTH DEFAULT_VALUE 3
set_parameter_property ADDR_WIDTH DISPLAY_NAME ADDR_WIDTH
set_parameter_property ADDR_WIDTH TYPE INTEGER
set_parameter_property ADDR_WIDTH UNITS None
set_parameter_property ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDR_WIDTH DESCRIPTION ""
set_parameter_property ADDR_WIDTH AFFECTS_GENERATION false
set_parameter_property ADDR_WIDTH HDL_PARAMETER true
add_parameter DEFAULT_ACTIVE INTEGER 1 ""
set_parameter_property DEFAULT_ACTIVE DEFAULT_VALUE 1
set_parameter_property DEFAULT_ACTIVE DISPLAY_NAME DEFAULT_ACTIVE
set_parameter_property DEFAULT_ACTIVE TYPE INTEGER
set_parameter_property DEFAULT_ACTIVE UNITS None
set_parameter_property DEFAULT_ACTIVE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DEFAULT_ACTIVE DESCRIPTION ""
set_parameter_property DEFAULT_ACTIVE AFFECTS_GENERATION false
set_parameter_property DEFAULT_ACTIVE HDL_PARAMETER true
add_parameter LOW_ACTIVE INTEGER 1 ""
set_parameter_property LOW_ACTIVE DEFAULT_VALUE 1
set_parameter_property LOW_ACTIVE DISPLAY_NAME LOW_ACTIVE
set_parameter_property LOW_ACTIVE TYPE INTEGER
set_parameter_property LOW_ACTIVE UNITS None
set_parameter_property LOW_ACTIVE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property LOW_ACTIVE DESCRIPTION ""
set_parameter_property LOW_ACTIVE AFFECTS_GENERATION false
set_parameter_property LOW_ACTIVE HDL_PARAMETER true
# | 
# +-----------------------------------


# +-----------------------------------
# | connection point s1_clock
add_interface s1_clock clock end
set_interface_property s1_clock clockRate 0
set_interface_property s1_clock ENABLED true

add_interface_port s1_clock avs_s1_clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s1_clock_reset
# | 
add_interface s1_clock_reset reset end
set_interface_property s1_clock_reset associatedClock s1_clock
set_interface_property s1_clock_reset synchronousEdges DEASSERT

set_interface_property s1_clock_reset ENABLED true

add_interface_port s1_clock_reset avs_s1_reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s1
# | 
add_interface s1 avalon end
set_interface_property s1 addressAlignment NATIVE
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock s1_clock
set_interface_property s1 associatedReset s1_clock_reset
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 isMemoryDevice false
set_interface_property s1 isNonVolatileStorage false
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 printableDevice false
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitStates 0
set_interface_property s1 readWaitTime 0
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0

set_interface_property s1 ENABLED true

add_interface_port s1 avs_s1_address address Input addr_width
add_interface_port s1 avs_s1_read read Input 1
add_interface_port s1 avs_s1_readdata readdata Output 8
add_interface_port s1 avs_s1_write write Input 1
add_interface_port s1 avs_s1_writedata writedata Input 8
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s1_export
# | 
add_interface s1_export conduit end

set_interface_property s1_export ENABLED true

add_interface_port s1_export avs_s1_export_seg7 export Output seg7_num*8
# | 
# +-----------------------------------
